### ISSUE TITLE
"Modify Scope Zoom" does not work

### ISSUE THREAD

**Issue by wanli1028** [RyMaxim/cotw-mod-builder#1]
Hey Bryan,I've found that"Modify Scope Zoom" does not work,please take a look,thanks a lot!

**Comment by wanli1028** [comment]
![屏幕截图 2024-07-28 010314](https://github.com/user-attachments/assets/7cf06f2f-68b9-4a1e-ae20-34656c255a96)

**Comment by RyMaxim** [comment]
This is fixed with the 2.1.2 release: https://github.com/RyMaxim/cotw-mod-builder/releases/tag/2.1.2
