### ISSUE TITLE
Error using new Lures mod building

### ISSUE THREAD

**Issue by lordbanastor** [RyMaxim/cotw-mod-builder#3]
When using the new Lures mod building option, I was presented with this error:

![image](https://github.com/user-attachments/assets/0d665a76-3ced-43a4-9904-dc4ec354c87b)

I guess the original file is pointing to the computer of the developer, but it's just a guess. Please call me if any other info is necessary.

**Comment by RyMaxim** [comment]
Hilarious. The definition of "it works fine on my machine" 😆 

Thanks for the quick report. I'll get this updated today.

**Comment by lordbanastor** [comment]
Problem solved with new release. Thank you!
