### ISSUE TITLE
It set off windows defender and opera scan

### ISSUE THREAD

**Issue by Nordigoistired** [RyMaxim/cotw-mod-builder#4]
i downloaded the latest version and it set off windows defender and opera's virus scan. the old mod builder didn't do that why does this one?

**Comment by RyMaxim** [comment]
The compiled .exes that I upload to the Releases page are built using pyinstaller, a free tool used to package Python scripts into .exe files. Unfortunately, pyinstaller can be used by anyone to compile any Python code into an executable, including malicious code. Software built with pyinstaller is often automatically flagged as a trojan/virus/malware as a result.

I currently scan all new builds with VirusTotal to see which AV scanners report malicious code. I then send a copy of the compiled .exe as well as a link to the source code here on GitHub to any companies whose scanner shows any detected vulnerabilities. Each vendor reviews the files and updates their scanner to remove the false positive results (which can take a few days).

I'm not sure how the previous developer may have been handling this differently but it's currently the best system I have without paying hundreds of dollars per year for a code signing certificate.
