### ISSUE TITLE
Can't change path

### ISSUE THREAD

**Issue by TravisUNT** [RyMaxim/cotw-mod-builder#6]
Unless I am missing something simple, there is no way to change the path to the game once it has been set. If set incorrectly, there's no way to remedy besides deleting the directory and re-copying from the 7z.

**Comment by RyMaxim** [comment]
Hey @TravisUNT. The path is saved to a `game_path.txt` file in the modbuilder folder that contains the path you chose. You can either edit that file with the correct path or just delete it and re-launch Mod Builder to pick the correct path. I'll add a button to the UI for this in the next version.

**Comment by RyMaxim** [comment]
A **(change path)** button was added in [2.1.6](https://github.com/RyMaxim/cotw-mod-builder/releases/tag/2.1.6) 🎉
